### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by okaday54** [okaday54/chat-space#5]
# IPアドレス
3.115.224.60

**Comment by yasunamiura** [comment]
岡田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**①グループ名と新着メッセージの下線をなくしましょう
②文頭にMember:を追加しましょう
③非同期・自動更新時にメッセージと画像を同時に投稿すると画像が表示されません
④「③のとき」にずっと自動更新が動いています**
<img width="1190" alt="ChatSpace" src="https://user-images.githubusercontent.com/52514431/76741108-52403280-67b2-11ea-8b34-e19848ee7234.png">
見本
<img width="1193" alt="ChatSpaceSample" src="https://user-images.githubusercontent.com/52514431/76741185-7996ff80-67b2-11ea-8ad9-623629bb6053.png">

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by okaday54** [comment]
変更が反映を確認する前にフォーム送ってしまいました。
再度送り直します

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の指摘事項全て確認しましたが、修正が確認できませんでした。
デプロイはお済みでしょうか？デプロイがうまくできていない可能性もありますので、本番環境にてご確認をお願い致します！

また、前回の指摘事項に加えて下記1点も修正をお願いしたいです。

**・画像を投稿したあと、同じ投稿がずっと繰り返されてしまう**

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naru6117** [comment]
再度のご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
